services:
  mysql:
    image: mysql:latest
    container_name: pupa_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pupa
      MYSQL_USER: pupa
      MYSQL_PASSWORD: pupa
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
