// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.3
// source: pupa_dog.proto

package pupa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DogIsGoodBoyV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DogIsGoodBoyV1Request) Reset() {
	*x = DogIsGoodBoyV1Request{}
	mi := &file_pupa_dog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogIsGoodBoyV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogIsGoodBoyV1Request) ProtoMessage() {}

func (x *DogIsGoodBoyV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_pupa_dog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogIsGoodBoyV1Request.ProtoReflect.Descriptor instead.
func (*DogIsGoodBoyV1Request) Descriptor() ([]byte, []int) {
	return file_pupa_dog_proto_rawDescGZIP(), []int{0}
}

func (x *DogIsGoodBoyV1Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DogIsGoodBoyV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsGoodBoy bool `protobuf:"varint,1,opt,name=is_good_boy,json=isGoodBoy,proto3" json:"is_good_boy,omitempty"`
}

func (x *DogIsGoodBoyV1Response) Reset() {
	*x = DogIsGoodBoyV1Response{}
	mi := &file_pupa_dog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogIsGoodBoyV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogIsGoodBoyV1Response) ProtoMessage() {}

func (x *DogIsGoodBoyV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_pupa_dog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogIsGoodBoyV1Response.ProtoReflect.Descriptor instead.
func (*DogIsGoodBoyV1Response) Descriptor() ([]byte, []int) {
	return file_pupa_dog_proto_rawDescGZIP(), []int{1}
}

func (x *DogIsGoodBoyV1Response) GetIsGoodBoy() bool {
	if x != nil {
		return x.IsGoodBoy
	}
	return false
}

var File_pupa_dog_proto protoreflect.FileDescriptor

var file_pupa_dog_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x75, 0x70, 0x61, 0x5f, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x70, 0x75, 0x70, 0x61, 0x22, 0x2b, 0x0a, 0x15, 0x44, 0x6f, 0x67, 0x49, 0x73, 0x47,
	0x6f, 0x6f, 0x64, 0x42, 0x6f, 0x79, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x16, 0x44, 0x6f, 0x67, 0x49, 0x73, 0x47, 0x6f, 0x6f, 0x64,
	0x42, 0x6f, 0x79, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0b, 0x69, 0x73, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x5f, 0x62, 0x6f, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x47, 0x6f, 0x6f, 0x64, 0x42, 0x6f, 0x79, 0x32, 0x59, 0x0a,
	0x0a, 0x44, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x44,
	0x6f, 0x67, 0x49, 0x73, 0x47, 0x6f, 0x6f, 0x64, 0x42, 0x6f, 0x79, 0x56, 0x31, 0x12, 0x1b, 0x2e,
	0x70, 0x75, 0x70, 0x61, 0x2e, 0x44, 0x6f, 0x67, 0x49, 0x73, 0x47, 0x6f, 0x6f, 0x64, 0x42, 0x6f,
	0x79, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x75, 0x70,
	0x61, 0x2e, 0x44, 0x6f, 0x67, 0x49, 0x73, 0x47, 0x6f, 0x6f, 0x64, 0x42, 0x6f, 0x79, 0x56, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x75,
	0x70, 0x61, 0x3b, 0x70, 0x75, 0x70, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pupa_dog_proto_rawDescOnce sync.Once
	file_pupa_dog_proto_rawDescData = file_pupa_dog_proto_rawDesc
)

func file_pupa_dog_proto_rawDescGZIP() []byte {
	file_pupa_dog_proto_rawDescOnce.Do(func() {
		file_pupa_dog_proto_rawDescData = protoimpl.X.CompressGZIP(file_pupa_dog_proto_rawDescData)
	})
	return file_pupa_dog_proto_rawDescData
}

var file_pupa_dog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pupa_dog_proto_goTypes = []any{
	(*DogIsGoodBoyV1Request)(nil),  // 0: pupa.DogIsGoodBoyV1Request
	(*DogIsGoodBoyV1Response)(nil), // 1: pupa.DogIsGoodBoyV1Response
}
var file_pupa_dog_proto_depIdxs = []int32{
	0, // 0: pupa.DogService.DogIsGoodBoyV1:input_type -> pupa.DogIsGoodBoyV1Request
	1, // 1: pupa.DogService.DogIsGoodBoyV1:output_type -> pupa.DogIsGoodBoyV1Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pupa_dog_proto_init() }
func file_pupa_dog_proto_init() {
	if File_pupa_dog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pupa_dog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pupa_dog_proto_goTypes,
		DependencyIndexes: file_pupa_dog_proto_depIdxs,
		MessageInfos:      file_pupa_dog_proto_msgTypes,
	}.Build()
	File_pupa_dog_proto = out.File
	file_pupa_dog_proto_rawDesc = nil
	file_pupa_dog_proto_goTypes = nil
	file_pupa_dog_proto_depIdxs = nil
}
